name: Verify
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
concurrency:
  group: ${{ github.repository }}-verify-${{ github.ref_name }}
  cancel-in-progress: false
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # The SonarQube scanner needs the full git history to determine blaming history.
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Run SonarQube analysis
        run: npm run analyze:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
